$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: green
endpoint_name: mlops-hudua-alias
model: azureml:mlopsmodel:1
code_configuration:
  code: scoring
  scoring_script: score.py
environment:
  image: amlhuduaname.azurecr.io/repo/env:1
instance_type: Standard_DS3_v2
instance_count: 1
