name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8.10
  - numpy=1.19.4
  - pandas=1.2.3
  - pip=21.2.4
  - scikit-learn=0.23.2
  - pip:    
      - azureml-defaults==1.39.0
      - azureml-inference-server-http
